name: etl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - openpyxl
  - pandas=2.1.4
  - numpy
  - pyarrow=14.0.2
  - fastparquet
  - jupyter
  - notebook
  - ipykernel
  - ipython
  - traitlets
  - pygments
  - typing-extensions
  - pip
  - pip:
      - langchain
      - faiss-cpu
      - unstructured
